### ISSUE TITLE
Rillaboom Level 37 Does not compute, Sp.D Incorrect.

### ISSUE THREAD

**Issue by miniMewtwo** [LegendaryPKMN/ivcalc#33]
Hi, when trying to calculate my Friend's Rillaboom"s possible IVs it keep telling me that The Sp.Defense stat is wrong.
I'm Afraid the I have no idea what the Effort Values for her Pokemon would be, and not entering anything in those slots hasn't stopped me from being able to check any of my own Pokemon, so I'm not sure if this is a bug or not.
![Rillaboom Issue](https://user-images.githubusercontent.com/57882458/69020420-49646d80-0a19-11ea-89b6-f6efa6ad3d8f.png)
![received_806569413111411](https://user-images.githubusercontent.com/57882458/69020423-49fd0400-0a19-11ea-874a-4023319edb67.jpeg)
![received_2626795690707301](https://user-images.githubusercontent.com/57882458/69020424-49fd0400-0a19-11ea-8220-bae7ca37c7ab.jpeg)

**Comment by Arty2** [comment]
Hi @miniMewtwo, indeed the calculator reports an error because your Pokemon needs to have its Effort Points entered. There is a way to reset them, but SAVE your game before doing that.

Feed your Pokémon as many of these berries as needed, to decrease the EVs of each stat, until the "stats hexagon" is blank:
- Pomeg Berry (-10 HP EVs)
- Kelpsy Berry (-10 Attack EVs)
- Qualot Berry (-10 Defense EVs)
- Hondew Berry (-10 Special Attack EVs)
- Grepa Berry (-10 Special Defense EVs)
- Tamato Berry (-10 Speed EVs)
