### ISSUE TITLE
Decidueye stat

### ISSUE THREAD

**Issue by K9-Hyp4H** [LegendaryPKMN/ivcalc#34]
When I tried calculating my Deidueye's IVs it claims that the values I entered are incorrect. However, on review I found that all the information is correct.(sorry for bad pic quality)
![WIN_20191130_17_35_54_Pro](https://user-images.githubusercontent.com/58369805/69903923-ecad6f00-1397-11ea-88f2-351ce6b98931.jpg)
![Sun   Moon Individual Value   Stat Calculator - LegendaryPKMN net - Google Chrome 30_11_2019 17_38_49](https://user-images.githubusercontent.com/58369805/69903987-b0c6d980-1398-11ea-8561-2e970e786de2.png)

**Comment by Arty2** [comment]
Hi @K9-Hyp4H, the calculator reports an error because your Pokemon needs to have its Effort Points entered. There is a way to reset them, but SAVE your game before doing that.

Feed your Pokémon as many of these berries as needed, to decrease the EVs of each stat, until the "stats hexagon" is blank:

    Pomeg Berry (-10 HP EVs)
    Kelpsy Berry (-10 Attack EVs)
    Qualot Berry (-10 Defense EVs)
    Hondew Berry (-10 Special Attack EVs)
    Grepa Berry (-10 Special Defense EVs)
    Tamato Berry (-10 Speed EVs)
